### PR TITLE
toggle open/close of options list when select box is clicked on

### PR DESCRIPTION
**Pull request by rovolution**
Submitting this PR that opens/closes the select box when the main select box element is clicked on. This resembles the default behavior of native select boxes.

For example, if the options list is already open, and the select box is clicked, the list will close.

If it the options list is closed, and the select box is clicked, the options list will open.

Let me know if you have any questions/comments.

And thanks again for this awesome plugin!

### CODE REVIEW

**Comment by rovolution** [comment]
@brentburg hey! I saw the new changes that you made to this plugin. Looks awesome! If I update this PR to make it merge-compatible, could I resubmit and potentially get it merged in? 

Thanks!

**Comment by brentburg** [comment]
@rovolution: Sure, that would be awesome.

**Comment by rovolution** [comment]
@brentburg updated the PR to be merge compatible and did some QA tests/ran the test suite.

let me know if i need to change anything. thanks

**Comment by brentburg** [comment]
It has been a busy week. I will review over the weekend. Thanks!

**Comment by aaronshaf** [comment]
@brentburg ^

**Comment by brentburg** [comment]
@aaronshaf do you want to review and merge. I need to be added to `instructure-react` since the repo got moved.

**Comment by brentburg** [comment]
@rovolution sorry for the delay. Thanks for the pull request!

**Pull request merged**
